name: Build Zed Stable

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  push:
    branches:
      - main

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-latest-release.outputs.version }}
      should-build: ${{ steps.check-release.outputs.should-build }}
    steps:
      - name: Get latest release version
        id: get-latest-release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/zed-industries/zed/releases/latest | jq -r '.tag_name')
          echo "Latest release version: $LATEST_RELEASE"
          if [[ "$LATEST_RELEASE" == "null" ]]; then
            echo "Latest release version is null. Skipping build."
            echo "version=null" >> $GITHUB_OUTPUT
            echo "should-build=false" >> $GITHUB_OUTPUT
          else
            echo "version=$LATEST_RELEASE" >> $GITHUB_OUTPUT
          fi

      - name: Check if release already exists
        id: check-release
        if: steps.get-latest-release.outputs.version != 'null'
        run: |
          # Get the latest release version from the previous step
          LATEST_RELEASE=${{ steps.get-latest-release.outputs.version }}

          # Check if a release with this version already exists
          RELEASE_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/$LATEST_RELEASE)
          if [[ "$RELEASE_EXISTS" == "200" ]]; then
            echo "Release $LATEST_RELEASE already exists. Skipping build."
            echo "should-build=false" >> $GITHUB_OUTPUT
          else
            echo "Release $LATEST_RELEASE does not exist. Proceeding with build."
            echo "should-build=true" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: windows-latest
    needs: get-version
    if: needs.get-version.outputs.should-build == 'true'
    strategy:
      matrix:
        backend: [vulkan, opengl]
        include:
          - backend: vulkan
            artifact_name: zed-release
            rustflags: ""
          - backend: opengl
            artifact_name: zed-release-opengl
            rustflags: "--cfg gles"

    steps:
      - name: Enable long paths in Git
        run: |
          git config --system core.longpaths true

      - name: Enable long paths in Windows
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Install PSToml module
        shell: pwsh
        run: Install-Module -Name PSToml -Scope CurrentUser -Force

      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout Zed
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: ${{ needs.get-version.outputs.version }}  # 使用获取的发布版本作为 ref  
          path: zed

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true
          target: wasm32-wasip1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.backend }}
          workspaces: "zed -> target"

      - name: Setup rustflags
        shell: pwsh
        run: ./Parse-Rustflags.ps1 ${{ matrix.rustflags }}

      - name: Build release
        working-directory: zed
        run: cargo build --release

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: zed/target/release/zed.exe

  release:
    runs-on: ubuntu-latest
    needs: [get-version, build]
    if: needs.get-version.outputs.should-build == 'true'
    permissions:
      contents: write

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release directories and zip
        run: |
          mkdir -p zed-release zed-release-opengl
          mv artifacts/zed-release/zed.exe zed-release/
          mv artifacts/zed-release-opengl/zed.exe zed-release-opengl/
          zip -r zed-windows-stable-${{ needs.get-version.outputs.version }}.zip zed-release/*
          zip -r zed-windows-stable-opengl-${{ needs.get-version.outputs.version }}.zip zed-release-opengl/*

      - name: Upload release build artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Stable Release ${{ needs.get-version.outputs.version }}
          tag_name: ${{ needs.get-version.outputs.version }}
          draft: false
          make_latest: true
          files: |
            zed-windows-stable-${{ needs.get-version.outputs.version }}.zip
            zed-windows-stable-opengl-${{ needs.get-version.outputs.version }}.zip