build:
  needs: check-and-trigger
  if: ${{ env.TRIGGER_BUILD == 'true' }}
  runs-on: windows-latest
  strategy:
    matrix:
      backend: [vulkan, opengl]
      include:
        - backend: vulkan
          artifact_name: zed-release
          rustflags: ""
        - backend: opengl
          artifact_name: zed-release-opengl
          rustflags: "--cfg gles"

  steps:
    - name: Enable long paths in Git
      run: |
        git config --system core.longpaths true

    - name: Enable long paths in Windows
      shell: powershell
      run: |
        New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
          -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

    - name: Checkout Zed repository
      uses: actions/checkout@v3
      with:
        repository: zed-industries/zed
        ref: ${{ env.LATEST_TAG }}  # 使用最新的稳定版标签

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        override: true

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.3
      with:
        key: ${{ matrix.backend }}-stable

    - name: Build release
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}
        CARGO_BUILD_JOBS: 2  # 设置并行任务数为 2
      run: cargo build --release --jobs 2

    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: target/release/zed.exe